// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBrozjHHZdybUAioeHyTc0m_rcDQT77BYU',
    appId: '1:795741398084:web:5483351d70a4c478158811',
    messagingSenderId: '795741398084',
    projectId: 'cafetaria-797c0',
    authDomain: 'cafetaria-797c0.firebaseapp.com',
    databaseURL: 'https://cafetaria-797c0-default-rtdb.firebaseio.com',
    storageBucket: 'cafetaria-797c0.appspot.com',
    measurementId: 'G-61HHT6NMBR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCox-QALQPqINFxV8snNS3rPTxN6kyAYIE',
    appId: '1:795741398084:android:d291816e85b39996158811',
    messagingSenderId: '795741398084',
    projectId: 'cafetaria-797c0',
    databaseURL: 'https://cafetaria-797c0-default-rtdb.firebaseio.com',
    storageBucket: 'cafetaria-797c0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyADTIQW9GBAzYh4dHGc7d2-VdcLufGIjUo',
    appId: '1:795741398084:ios:9976834f8d0ed154158811',
    messagingSenderId: '795741398084',
    projectId: 'cafetaria-797c0',
    databaseURL: 'https://cafetaria-797c0-default-rtdb.firebaseio.com',
    storageBucket: 'cafetaria-797c0.appspot.com',
    androidClientId: '795741398084-3409rq52mqvufvima3td3qm5c6f54bn3.apps.googleusercontent.com',
    iosClientId: '795741398084-ef1q94l9ts84i4hn00h5gkcvgcp7le7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyADTIQW9GBAzYh4dHGc7d2-VdcLufGIjUo',
    appId: '1:795741398084:ios:9976834f8d0ed154158811',
    messagingSenderId: '795741398084',
    projectId: 'cafetaria-797c0',
    databaseURL: 'https://cafetaria-797c0-default-rtdb.firebaseio.com',
    storageBucket: 'cafetaria-797c0.appspot.com',
    androidClientId: '795741398084-3409rq52mqvufvima3td3qm5c6f54bn3.apps.googleusercontent.com',
    iosClientId: '795741398084-ef1q94l9ts84i4hn00h5gkcvgcp7le7b.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterProjects',
  );
}
